name: CI/CD Heroes

on:
  push:
    paths:
      - 'heroes/**'
  pull_request:
    paths:
      - 'heroes/**'

jobs:
  deploy-heroes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v3

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@v1

      - name: Validar bundle
        working-directory: heroes
        run: databricks bundle validate

      - name: Deploy bundle para o Databricks
        working-directory: heroes
        run: databricks bundle deploy
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}


